### ISSUE TITLE
pgrtk-0.3.4-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by wharvey31** [Sema4-Research/pgr-tk#1]
Hello,

Can you please list which Linux distributions the wheels support? I have tried on both Ubuntu 20.04 and CentOS7, and both give the error of  "not a supported wheel on this platform" when trying to pip install?

Thank you!

**Comment by cschin** [comment]
@wharvey31 which exact `.whl` do you install?  the python `.whl` dependence is tricky as it depends on your python installation. Is it possible you try out build with a docker container to isolate the dependence?

**Comment by cschin** [comment]
You might want to update your `pip` by `pip install --upgrade pip`. Also, you can use `pip debug --verbose` to check the supported wheel platform of you python installation.

**Comment by cschin** [comment]
no further response from OP. close.
